export default [
  {
    id: 2,
    label: "پرسنل مستعفی: ",
    name: "applicant",
    placeholder: "جستجو . . .",
    type: "select",
    md: "4",
    lg: "3",
    xxl: "2",
  },
  {
    id: 3,
    label: "وضعیت درخواست: ",
    name: "status",
    placeholder: "جستجو . . .",
    type: "select",
    md: "4",
    lg: "3",
    xxl: "2",
  },
  {
    id: 3.5,
    label: "علت ترک خدمت: ",
    name: "reasonLeavingCase",
    placeholder: "جستجو . . .",
    type: "select",
    md: "4",
    lg: "3",
    xxl: "2",
  },
  {
    id: 3.6,
    label: "شرکت: ",
    name: "company",
    placeholder: "جستجو . . .",
    type: "select",
    md: "4",
    lg: "3",
    xxl: "2",
  },
  {
    id: 3.78,
    label: "واحد: ",
    name: "department",
    placeholder: "جستجو . . .",
    type: "select",
    md: "4",
    lg: "3",
    xxl: "2",
  },
  {
    id: 4,
    label: "از تاریخ: ",
    name: "fromDate",
    type: "date",
    inputFormat: "YYYY-MM-DD",
    isGregorian: false,
    timePicker: false,
    md: "4",
    lg: "3",
    xxl: "2",
  },
  {
    id: 5,
    label: "تا تاریخ :",
    name: "toDate",
    type: "date",
    inputFormat: "YYYY-MM-DD",
    isGregorian: false,
    timePicker: false,
    md: "4",
    lg: "3",
    xxl: "2",
  },
];
